name: Test Deployment

on:
  workflow_dispatch:

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK OSSRH
      uses: actions/setup-java@v4
      with: # running setup-java again overwrites the settings.xml
        distribution: 'temurin'
        java-version: '17'
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Publish to OSSRH
      run: |
        modules=("bom")
        dependency_management_block=$(grep -ozP '<dependencyManagement>(\r|\n|.)*<\/dependencyManagement>' 'bom/pom.xml' | tr -d '\0')
        modules+=($(echo $dependency_management_block | grep -oP '(?<=<artifactId>)[^<]+'))
        printf -v modules_joined '%s,' "${modules[@]}"
        modules_arg=$(echo "${modules_joined%,}")
        ./mvnw -B deploy -pl "$modules_arg" -am -T2C -Possrh -DskipTests
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.S01_OSS_SONATYPE_MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.S01_OSS_SONATYPE_MAVEN_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
